### ISSUE TITLE
CO2 Emissions by Country Experiment

### ISSUE THREAD

**Issue by aboydnw** [US-GHG-Center/veda-config-ghg#389]
## Context

We would like to give users access to state-level or other regionally aggregated emissions based on the [OCO2 dataset](https://earth.gov/ghgcenter/data-catalog/oco2-mip-co2budget-yeargrid-v1).

Users currently have the option to compute zonal statistics on the fly from total emissions datasets. However, the officially approved methodology requires a different formula, involving several partial products, which we currently do not host. In short, users can currently get the **zonal median of the sum of constituent products** ($\overline{ \sum_{p} x }$), while the official methodology is to calculate the **sum of the zonal medians of the constituent products** ($\sum_{p} \bar{x}$).

One option would be to host all the constituent datasets and implement a custom formula. Definitely possible, but a lot of work.

A quick experiment could be to pre-compute the estimates and display them in the GHG Center and gather responses from users who want to compute the same metric for a custom area.

## Experiment

Brendan Byrne has a csv of accurate country totals already available in his Jupyter Notebook. We could provide access to this data in the GHGC Portal and determine how many people want something more than what is available in this csv file. 

Potential gaps users might see with this csv file:
1. Not able to combine countries or create irregular shapes (like regions of the world, alliances, etc)
2. Smaller than country units, like states
3. Not able to explore different temporal ranges or resolutions

## Acceptance Criteria
- [ ] Information in the csv file is available in the GHGC Portal
- [ ] We are able to quantify how many users want additional functionality with this data, and some rough understanding of what type of functionality

**Comment by Jeanne-le-Roux** [comment]
This is the specific dataset referenced: https://earth.gov/ghgcenter/data-catalog/oco2-mip-co2budget-yeargrid-v1

If you were to calculate the total CO2 emission for _X_ year over _X_ area of interest (e.g. for a given country) using the 1x1 degree data currently provided on the GHG Center portal, you would get a result inconsistent with the country level totals provided in the [related publication](https://essd.copernicus.org/articles/15/963/2023/), because it uses a different underlying methodology.  [Section 3 of the publication](https://essd.copernicus.org/articles/15/963/2023/#section3) provides some insight to how the country-level total data were derived differently than the 1x1 degree satellite data. 

It was proposed that the user have the ability to select a country mask (or any AOI) and request CO2 emissions totals with the correct underlying methodology applied in the backend. We first want to investigate whether this would bring significant user value (as outlined above) before moving forward with trying to implement something like this.

**Comment by aboydnw** [comment]
@Jeanne-le-Roux @siddharth0248 @deborahUAH What if we made this the use case for the Microsoft Geo Copilot proof of concept? It might be a little more complicated than we had hoped for, but would be very tangible

If I remember correctly, there might be a few steps to take in order to make this a reality:
1. Ingest the underlying datasets that are used in this calculation (is that accurate?)
2. Codify the model used in the linked publication
3. Allow users to query these model results (how would we then visualize it?)

Might be a bit complicated to start with, but could be a good guide post

cc @xhagrg @slesaad @j08lue @freitagb

**Comment by j08lue** [comment]
I updated the formulations in the [issue description](https://github.com/US-GHG-Center/veda-config-ghg/issues/389#issue-2309009438) above ☝️to clarify that the information in the GHG Center is **accurate**, just not sufficient for calculating accurate regional totals (requires sum of medians, not median of sum).

**Comment by j08lue** [comment]
> If I remember correctly, there might be a few steps to take in order to make this a reality

@aboydnw, the steps you listed are correct. But this is not a case for machine learning / LLM, etc. 

Data-analysis-wise, the problem is super simple - just some arithmetics.

It would also be super easy to build a custom service that makes this calculation.

The question is whether it makes sense, strategically, to maintain a custom analysis service for one particular dataset or type of calculation (maybe it can be somewhat generalized).

**Comment by aboydnw** [comment]
I'm game for starting with the first experiment. In that case, we would need the csv or another way to display the summarized data

**Comment by Jeanne-le-Roux** [comment]
Country totals can be accessed here (CSV, XLS or NetCDF format): https://ceos.org/gst/carbon-dioxide.html

In the exploration environment we're currently only displaying the following variables (there's many more in the CSV):

- LNLGIS NBE & LNLGIS NBE unc  
- LNLGIS NCE &  LNLGIS NCE unc
- LNLGIS dC_loss & LNLGIS dC_loss unc
- Wood+Crop & Wood+Crop unc >> (in the gridded data Wood & Crop are separated into 2 layers)
- Rivers & Rivers unc
- FF & FF unc

If we wanted to further down-select the number of variables to display for the country totals I would defer to the data providers to ask for their preference.

**Comment by j08lue** [comment]
From data to algorithms to applications - the increase in (user) value we are targeting here is quite in line with the principle [nicely expressed by Joe Morrison](https://joemorrison.substack.com/p/nobody-wants-your-fancy-algorithm).

**Comment by aboydnw** [comment]
This is a big table with lots of variables. I think another experiment could be simply directing users to the existing page (like you did above @Jeanne-le-Roux ) and tracking how many people click on it. That would be a sign that people actually value these country totals before we spend time figuring out how to best display all this information.

Side note: my understanding of our decision maker users is that these are sub-national (state, city, etc) government workers and so these country totals might not be super useful. Another reason I'd push for a lower cost experiment before taking up development hours.
cc @freitagb

**Comment by aboydnw** [comment]
closing as not planned, can reopen if there is significant value here
